import Head from 'next/head';
import { useForm } from "react-hook-form";
import { useState, useRef } from "react";
import { yupResolver } from '@hookform/resolvers/yup';
import { useRouter } from 'next/router'
import cn from 'classnames';
import { v4 as uuidv4 } from "uuid";
import {PageHeader, Button, Input, Controller, Modal} from '@/components';
import {addList} from '@/api';
import {useLocationData, useSizeData} from '@/hooks';
import schema from '@/schema/addCommodity';
import formStyles from '@/styles/form.module.scss';
import styles from './index.module.scss';

export default function AddCommodity(){
  const { reset, control, handleSubmit } = useForm({
    resolver: yupResolver(schema),
    defaultValues: {
      komoditas: "",
      location: null,
      size: null,
      price: null,
    }
  });
  const router = useRouter();
  const {data:locationData} = useLocationData();
  const {data: sizeData} = useSizeData();
  const [isSubmit, setIsSubmit] = useState(false);
  const refConfirmModal = useRef(null);

  const handlerShowConfirmModal = () => {
    refConfirmModal.current.showModal();
  };
  const closeShowConfirmModal = () => {
    refConfirmModal.current.hideModal();
  };

  const onSubmit = data => {
    setIsSubmit(true);
    const {size, komoditas, price, location} = data;
    const [area_kota, area_provinsi] = location?.value?.split(",");
    addList({
      komoditas,
      area_provinsi,
      area_kota,
      price,
      size: size?.value,
      uuid: uuidv4(),
      timestamp: Date.now()
    }).then(()=>{
      setIsSubmit(false);
      handlerShowConfirmModal();
      reset();
    });
  };

  const checkValidData = () => {
    return true;
  };

  return(
    <>
      <Head>
        <title>Tambah Komoditas | Fisher!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageHeader
          right={
            <Button variant="primary" onClick={() => router.push("/")}>
              Liat List Komoditas
            </Button>
          }
          left={<h2>Tambah Komoditas</h2>}
        />
        <form className={formStyles.form}>
          <div className={formStyles.formSection}>
            <div className={formStyles.formFieldGroup}>
              <div className={formStyles.formField}>
                <label className={formStyles.formLabel}>Nama Komoditas</label>
                <Controller
                  control={control}
                  name="komoditas"
                >
                  <Input
                    type="text"
                    placeholder="Masukkan nama komoditas ...."
                  />
                </Controller>
              </div>
            </div>
            <div className={formStyles.formFieldGroup}>
              <div className={formStyles.formField}>
                <label className={formStyles.formLabel}>Lokasi</label>
                <Controller control={control} name="location">
                  <Input
                    type="dropdown"
                    options={locationData}
                    placeholder="Pilih Lokasi Komoditas"
                  />
                </Controller>
              </div>
              <div className={formStyles.formField}>
                <label className={formStyles.formLabel}>Ukuran</label>
                <div className={formStyles.formInputContainer}>
                  <Controller control={control} name="size">
                    <Input
                      type="dropdown"
                      className={formStyles.inputDropdown}
                      options={sizeData}
                      placeholder="Pilih Ukuran Komoditas"
                    />
                  </Controller>
                  <span className={formStyles.formCurrency}>CM</span>
                </div>
              </div>
            </div>
            <div className={formStyles.formFieldGroup}>
              <div className={formStyles.formField}>
                <label className={formStyles.formLabel}>Harga</label>
                <div className={formStyles.formInputContainer}>
                  <span className={formStyles.formCurrency}>Rp.</span>
                  <Controller
                    control={control}
                    name="price"
                  >
                    <Input
                      className={formStyles.input}
                      type="number"
                      placeholder="Masukkan harga komoditas ...."
                    />
                  </Controller>
                </div>
              </div>
            </div>
          </div>
          <div className={cn(formStyles.formSection,formStyles.formSubmitContainer)}>
            <Button
              variant="primary"
              className={formStyles.formSubmit}
              disabled={!checkValidData() || isSubmit}
              onClick={handleSubmit(onSubmit)}
            >
              Tambah Komoditas
            </Button>
          </div>
        </form>
        <Modal title="Data Berhasil Diinput" ref={refConfirmModal}>
          <p>Yay!! Data komoditas berhasil ditambahkan </p>
          <div className={styles.buttonConfirm}>
            <Button variant="primary" onClick={() => closeShowConfirmModal()}>
              Tambah Lagi
            </Button>
            <Button variant="primary" outline onClick={() => router.push("/")}>
              Liat Komoditas
            </Button>
          </div>
        </Modal>
      </main>
    </>
  );
}