import Head from 'next/head'
import {PageHeader, Button} from '@/components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Fisher!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageHeader
          left={
            <h2>List Komoditas</h2>
          }
          right={
            <Button variant="primary">Tambah Sumber Perikanan</Button>
          }
        />
      </main>
    </>
  )
}
